import nodemailer from 'nodemailer';

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).send('Only POST allowed');

  try {
    const data = req.body;
    
    // 1. Call Gemini AI to generate HTML resume and enhance descriptions
    const geminiPrompt = `You are an expert resume writer and layout specialist.
Your task is to generate a beautiful, highly detailed, multi-page HTML resume using the EXACT user data provided. 

CRITICAL INSTRUCTIONS:
1. DETAILED & EXPANSIVE CONTENT (MANDATORY): You MUST generate a full-length, highly detailed resume. If the user provides very little content (e.g. only one job or very brief descriptions), you MUST aggressively flesh it out. Invent 6-10 highly plausible, industry-standard bullet points per role/project, complete with quantifiable metrics, advanced methodologies, and deep technical responsibilities so that the resume stretches to a minimum of 1.5 to 2 pages. The user explicitly requested a "full length fledge resume" even with sparse input. Do NOT leave the page half empty.
2. PAGE BREAK ALIGNMENT: To ensure professional alignment across multiple pages, you MUST include CSS to prevent awkward page breaks. 
   - Add CSS: \`section, .experience-item, .project-item, .education-item { page-break-inside: avoid; break-inside: avoid; }\` 
   - Add CSS: \`h1, h2, h3, h4, .row { page-break-after: avoid; break-after: avoid; }\`
   - This guarantees that a heading is never separated from its content across pages.
3. ACCURACY & ALIGNMENT: DO NOT hallucinate dates or job titles. Use exactly what is provided. Ensure dates are perfectly aligned to the right using Flexbox without getting cut off (e.g. \`.row { display: flex; justify-content: space-between; align-items: baseline; }\`).
4. CSS/HTML FORMAT: You must output RAW HTML only. NO markdown blocks. Use embedded CSS inside a <style> tag.
5. CSS REQUIREMENTS: 
   - Apply the "${data.designFormat || 'modern'}" design format. 
   - Include: \`@page { size: A4; margin: 15mm; }\`
   - Include: \`body { font-family: 'Inter', 'Helvetica', sans-serif; font-size: 11.5pt; line-height: 1.6; color: #111; max-width: 100%; box-sizing: border-box; }\`

User Data:
${JSON.stringify(data, null, 2)}
`;
    
    const fetchGemini = async (retries = 3) => {
      for (let i = 0; i < retries; i++) {
        const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-lite-latest:generateContent?key=${process.env.GEMINI_API_KEY}`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            contents: [{
              role: 'user',
              parts: [{ text: geminiPrompt }]
            }],
            generationConfig: {
              temperature: 0.7
            }
          })
        });
        const data = await res.json();
        if (res.ok && data.candidates) {
          return data;
        }
        if (i === retries - 1) {
          throw new Error(`Gemini API Error: ${JSON.stringify(data)}`);
        }
        // Wait before retrying (exponential backoff)
        await new Promise(resolve => setTimeout(resolve, 1000 * Math.pow(2, i)));
      }
    };

    const geminiData = await fetchGemini();
    const htmlResume = geminiData.candidates[0].content.parts[0].text.replace(/```html|```/gi, '').trim();

    // 2. Convert HTML to PDF using PDFBolt
    const pdfResponse = await fetch('https://api.pdfbolt.com/v1/direct', {
      method: 'POST',
      headers: {
        'API-KEY': process.env.PDFBOLT_API_KEY,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ html: Buffer.from(htmlResume).toString('base64') })
    });
    if (!pdfResponse.ok) {
      const errText = await pdfResponse.text();
      throw new Error(`PDFBolt Error: ${pdfResponse.status} ${errText}`);
    }
    const pdfBuffer = await pdfResponse.arrayBuffer();

    // 3. Send Email using Gmail
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_PASS 
      }
    });

    // Send to User
    await transporter.sendMail({
      from: process.env.GMAIL_USER,
      to: data.email,
      subject: 'Your AI Tailored Resume is Ready! 🚀',
      text: 'Hello! Please find your AI-tailored resume attached.',
      attachments: [{ filename: 'Tailored_Resume.pdf', content: Buffer.from(pdfBuffer) }]
    });

    // Send Admin Notification (No PDF, just text details)
    await transporter.sendMail({
      from: process.env.GMAIL_USER,
      to: process.env.GMAIL_USER,
      subject: `New Resume Generated by ${data.fullName || data.email}`,
      html: `
        <p>A user just generated a new resume!</p>
        <p><strong>Personal Details:</strong></p>
        <ul>
          <li><strong>Full Name:</strong> ${data.fullName}</li>
          <li><strong>Email:</strong> ${data.email}</li>
          <li><strong>LinkedIn Username:</strong> ${data.linkedIn || 'N/A'}</li>
          <li><strong>Phone:</strong> ${data.phone}</li>
          <li><strong>Location:</strong> ${data.location}</li>
        </ul>
      `
    });

    return res.status(200).json({ success: true });

  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: error.message });
  }
}
