import nodemailer from 'nodemailer';

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).send('Only POST allowed');

  try {
    const data = req.body;
    
    // 1. Call Gemini AI to generate HTML resume and enhance descriptions
    const geminiPrompt = `You are an expert resume designer and ATS-friendly format specialist. Output ONLY a clean, professional HTML resume based on the following user data.

CRITICAL REQUIREMENTS:
1. STRICTLY ONE PAGE: The output MUST fit entirely on a single A4 page. 
   - Include this CSS: \`@page { size: A4; margin: 10mm; }\` and \`body { width: 210mm; height: 297mm; box-sizing: border-box; margin: 0 auto; overflow: hidden; }\`
   - Use compact fonts (10pt-11pt for body, 14pt-16pt for headings), tight line-height (1.25), and minimal margins/padding.
   - Summarize and condense descriptions into exactly 2-3 short bullet points per role so it never overflows.
2. PERFECT ALIGNMENT & ACCURACY: Use Flexbox/Grid for perfect horizontal alignment of dates, job titles, and locations. Do not hallucinate any data.
3. THEME: Apply the "${data.designFormat || 'modern'}" design format using embedded CSS.
   - modern: Clean, grid-based layout, subtle gray accents.
   - professional: Traditional corporate layout, navy blue headers, clean layout.
   - creative: Bold header, unique color accents, modern layout.
   - minimalist: Ultra-clean, monochrome, elegant typography.
4. Enhance descriptions to be highly professional but concise.
5. NO MARKDOWN: Output RAW HTML only. Do not include \`\`\`html tags.

User Data: ${JSON.stringify(data)}`;
    
    const fetchGemini = async (retries = 3) => {
      for (let i = 0; i < retries; i++) {
        const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${process.env.GEMINI_API_KEY}`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            contents: [{
              role: 'user',
              parts: [{ text: geminiPrompt }]
            }],
            generationConfig: {
              temperature: 0.7
            }
          })
        });
        const data = await res.json();
        if (res.ok && data.candidates) {
          return data;
        }
        if (i === retries - 1) {
          throw new Error(`Gemini API Error: ${JSON.stringify(data)}`);
        }
        // Wait before retrying (exponential backoff)
        await new Promise(resolve => setTimeout(resolve, 1000 * Math.pow(2, i)));
      }
    };

    const geminiData = await fetchGemini();
    const htmlResume = geminiData.candidates[0].content.parts[0].text.replace(/```html|```/gi, '').trim();

    // 2. Convert HTML to PDF using PDFBolt
    const pdfResponse = await fetch('https://api.pdfbolt.com/v1/direct', {
      method: 'POST',
      headers: {
        'API-KEY': process.env.PDFBOLT_API_KEY,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ html: Buffer.from(htmlResume).toString('base64') })
    });
    if (!pdfResponse.ok) {
      const errText = await pdfResponse.text();
      throw new Error(`PDFBolt Error: ${pdfResponse.status} ${errText}`);
    }
    const pdfBuffer = await pdfResponse.arrayBuffer();

    // 3. Send Email using Gmail
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_PASS 
      }
    });

    // Send to User
    await transporter.sendMail({
      from: process.env.GMAIL_USER,
      to: data.email,
      subject: 'Your AI Tailored Resume is Ready! 🚀',
      text: 'Hello! Please find your AI-tailored resume attached.',
      attachments: [{ filename: 'Tailored_Resume.pdf', content: Buffer.from(pdfBuffer) }]
    });

    // Send Admin Notification (No PDF, just text details)
    await transporter.sendMail({
      from: process.env.GMAIL_USER,
      to: process.env.GMAIL_USER,
      subject: `New Resume Generated by ${data.fullName || data.email}`,
      html: `
        <p>A user just generated a new resume!</p>
        <p><strong>Personal Details:</strong></p>
        <ul>
          <li><strong>Full Name:</strong> ${data.fullName}</li>
          <li><strong>Email:</strong> ${data.email}</li>
          <li><strong>LinkedIn Username:</strong> ${data.linkedIn || 'N/A'}</li>
          <li><strong>Phone:</strong> ${data.phone}</li>
          <li><strong>Location:</strong> ${data.location}</li>
        </ul>
      `
    });

    return res.status(200).json({ success: true });

  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: error.message });
  }
}
